package proyectofinal_tap;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class Login extends javax.swing.JFrame {

    //Frame1 - Administrador y Jefes de areas
    Frame_JA_A p1 = new Frame_JA_A();
    //Frame2 - Empleados
    Frame_Empleado p2 = new Frame_Empleado();
    private Image imagenOriginal;

    public Login() {
        initComponents();
        setLocationRelativeTo(null); //Centrar Frame
        //Icono de la pestaña
        setIconImage(new ImageIcon(getClass().getResource("/recursos/logo2 - copia.jpeg")).getImage());

        // Cargar imagen original del recurso
        ImageIcon icon = new ImageIcon(getClass().getResource("/recursos/L.jpeg"));
        imagenOriginal = icon.getImage();

        // Escalar imagen al tamaño actual del jLabel2
        escalarImagen();

        // Detectar cambio de tamaño del JLabel para reescalar la imagen
        jLabel2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                escalarImagen();
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
     private String obtenerArea(){
        String area = jTextField1.getText().trim().toLowerCase();
    switch (area) {
        case "ensamblaje":
        case "bodega":
        case "reparto":
        case "manofactura":
        case "recursoshumanos":
        case "empleado":
            return area;
        default:
            return "area no encontrada";
    }
        
    
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JBIniciar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NOMBRE DE LA EMPRESA");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JBIniciar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JBIniciar.setText("Iniciar Sesion");
        JBIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBIniciarActionPerformed(evt);
            }
        });
        getContentPane().add(JBIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 140, 30));

        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setText("Forgot password?");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/L.jpeg"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(400, 204));
        jLabel2.setMinimumSize(new java.awt.Dimension(400, 204));
        jLabel2.setPreferredSize(new java.awt.Dimension(400, 204));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 230, 170));

        jTextField1.setToolTipText("");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 220, -1));
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 220, -1));

        jLabel3.setText("Contraseña");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel4.setText("LOGIN");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 130, 60));

        jLabel6.setText("icon1");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel7.setText("Usuario");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        jLabel9.setText("icon2");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jButton3.setText("Regresar");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 130, 30));

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Fondo - copia.jpg"))); // NOI18N
        jLabel10.setAutoscrolls(true);
        jLabel10.setMaximumSize(new java.awt.Dimension(550, 240));
        jLabel10.setMinimumSize(new java.awt.Dimension(550, 240));
        jLabel10.setName(""); // NOI18N
        jLabel10.setOpaque(true);
        jLabel10.setPreferredSize(new java.awt.Dimension(550, 240));
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBIniciarActionPerformed
    String areaIngresada = jTextField1.getText().trim().toLowerCase();
    String password = new String(jPasswordField1.getPassword());
    String areaValidada = obtenerArea();

    // Validar si el área ingresada es conocida
    if (areaValidada.equals("area no encontrada")) {
        JOptionPane.showMessageDialog(this, "Área no válida. Intente nuevamente.");
        return;
    }

    // Acceso a recursos humanos
    if (areaIngresada.equalsIgnoreCase("recursoshumanos") ) {
        new Frame_JA_A().setVisible(true);
        dispose();
    }
    // Acceso a áreas como ensamblaje, bodega, reparto, manofactura
    else if (areaIngresada.equals(areaValidada) && password.equals("123456789")) {
        new Frame_JA_A().setVisible(true);
        dispose();
    }
    // Acceso para empleados de piso
    else if (areaIngresada.equals("empleado")) {
        new Frame_Empleado().setVisible(true);
        dispose();
    }
    // Si ninguna coincide
    else {
        JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos.");
    }
            
    }//GEN-LAST:event_JBIniciarActionPerformed
   
    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        L1 a = new L1();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3MouseClicked

   
    
    /**
     * @param args the command line arguments
     */
    private void escalarImagen() {
        if (imagenOriginal != null) {
            int ancho = jLabel2.getWidth();
            int alto = jLabel2.getHeight();
            if (ancho > 0 && alto > 0) {
                Image imagenEscalada = imagenOriginal.getScaledInstance(ancho, alto, Image.SCALE_SMOOTH);
                jLabel2.setIcon(new ImageIcon(imagenEscalada));
            }
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBIniciar;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
